-- v4.9.2 — Articles (Epic 9b)
-- An auto-published feed of modeling findings. Rows are generated by the cron
-- pipeline (pipeline/articles_generate.py) from E3's environmental/team-scheme
-- context artifact (pipeline/artifacts/context_report.json): each notable
-- weather / pace / pass-rate / venue signal becomes a human-readable article.
--
-- Two-plane fit (docs/architecture/ARCHITECTURE.md): PUBLIC READ (anon +
-- authenticated) — published findings are public editorial derived from public
-- catalog data. WRITES are service-role only (the pipeline); no anon/auth mutate
-- policy, so RLS denies them. Idempotent + safe to re-run.
--
-- E9a search (search_index.py → article_rows) indexes this table by
-- `id,title,slug,summary` and deep-links to `/articles/<slug>`; those four
-- columns are the stable contract it reads.

-- ------------------------------------------------------------
-- ARTICLES — one row per published finding. `slug` is the stable, URL-safe key
-- the generator upserts on (so a re-run overwrites in place, id stays fixed).
-- ------------------------------------------------------------
create table if not exists public.articles (
  id           uuid primary key default gen_random_uuid(),
  slug         text not null unique,          -- URL key: /articles/<slug>
  title        text not null,                 -- headline
  summary      text not null,                 -- one-line dek (search sublabel + card)
  body         text not null,                 -- article prose (blank-line paragraphs)
  category     text not null default 'context', -- 'weather' | 'pace' | 'passing' | 'venue' | 'context'
  source       text,                          -- provenance line (artifact + free-tier)
  published_at timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

-- Feed reads order by recency; category filter is cheap alongside it.
create index if not exists articles_published_idx
  on public.articles (published_at desc);

alter table public.articles enable row level security;

drop policy if exists "Public read articles" on public.articles;
create policy "Public read articles"
  on public.articles for select
  to anon, authenticated
  using (true);
-- (no insert/update/delete policy → service-role generator bypasses RLS;
--  anon/authenticated cannot mutate.)
