#!/usr/bin/env python3
"""Regenerate frontend/lib/schedule2026.ts from the 2026-27 NFL schedule xlsx.

The xlsx lives outside the repo (uploaded artifact); this keeps regeneration
reproducible while the committed output stays a static, dependency-free TS module.

Usage:
    python3 frontend/scripts/gen_schedule2026.py [path/to/schedule.xlsx]

Requires openpyxl (dev-only, never bundled). Sheet "Schedule": col A = full team
name, cols B..S = weeks 1..18, cell = opponent code ("@XXX" away, "XXX" home,
"BYE" = bye). Opponent codes already match our Sleeper codes (WAS, LAR, ...).
"""
from __future__ import annotations

import sys
from pathlib import Path

import openpyxl

DEFAULT_XLSX = (
    "/Users/andrew/.claude/uploads/0344d971-6de4-4a38-b9df-8d624c433311/"
    "414b63d2-202627nflschedule.xlsx"
)
OUT = Path(__file__).resolve().parents[1] / "lib" / "schedule2026.ts"

# Full team name (col A) -> our code. Codes are the 32 opponent codes used in the
# sheet cells, which already equal our Sleeper codes (byeWeeks.ts BYE_WEEKS_2026).
NAME_TO_CODE = {
    "Arizona Cardinals": "ARI", "Atlanta Falcons": "ATL", "Baltimore Ravens": "BAL",
    "Buffalo Bills": "BUF", "Carolina Panthers": "CAR", "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN", "Cleveland Browns": "CLE", "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN", "Detroit Lions": "DET", "Green Bay Packers": "GB",
    "Houston Texans": "HOU", "Indianapolis Colts": "IND", "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KC", "Las Vegas Raiders": "LV", "Los Angeles Chargers": "LAC",
    "Los Angeles Rams": "LAR", "Miami Dolphins": "MIA", "Minnesota Vikings": "MIN",
    "New England Patriots": "NE", "New Orleans Saints": "NO", "New York Giants": "NYG",
    "New York Jets": "NYJ", "Philadelphia Eagles": "PHI", "Pittsburgh Steelers": "PIT",
    "Seattle Seahawks": "SEA", "San Francisco 49ers": "SF", "Tampa Bay Buccaneers": "TB",
    "Tennessee Titans": "TEN", "Washington Commanders": "WAS",
}

WEEKS = 18


def parse(xlsx: str) -> dict[str, list[dict]]:
    wb = openpyxl.load_workbook(xlsx, data_only=True)
    ws = wb["Schedule"]
    out: dict[str, list[dict]] = {}
    for r in range(2, 34):
        name = ws.cell(r, 1).value
        if not name:
            continue
        code = NAME_TO_CODE.get(name)
        if not code:
            raise SystemExit(f"Unknown team name in xlsx: {name!r}")
        weeks: list[dict] = []
        for w in range(WEEKS):
            raw = ws.cell(r, 2 + w).value
            if raw is None:
                raise SystemExit(f"Missing cell for {code} week {w + 1}")
            raw = str(raw).strip()
            if raw == "BYE":
                weeks.append({"opponent": "BYE", "home": None})
            else:
                home = not raw.startswith("@")
                weeks.append({"opponent": raw.lstrip("@"), "home": home})
        out[code] = weeks
    if len(out) != 32:
        raise SystemExit(f"Expected 32 teams, got {len(out)}")
    _reconcile_neutral(out)
    return out


def _reconcile_neutral(out: dict[str, list[dict]]) -> None:
    """Neutral-site games (international) list both teams without '@', so the two
    home flags aren't opposite. The xlsx lacks true home/away there → mark neutral
    (home = None) on both sides. Also validates opponent symmetry."""
    for t, weeks in out.items():
        for i, g in enumerate(weeks):
            if g["opponent"] == "BYE":
                continue
            back = out[g["opponent"]][i]
            if back["opponent"] != t:
                raise SystemExit(
                    f"Schedule asymmetry: {t} wk{i + 1} vs {g['opponent']}, "
                    f"but {g['opponent']} wk{i + 1} vs {back['opponent']}"
                )
            if g["home"] is not None and back["home"] == g["home"]:
                g["home"] = None
                back["home"] = None


def emit(schedule: dict[str, list[dict]]) -> str:
    lines: list[str] = []
    for code in sorted(schedule):
        cells = []
        for g in schedule[code]:
            home = "null" if g["home"] is None else str(g["home"]).lower()
            cells.append(f'{{ opponent: "{g["opponent"]}", home: {home} }}')
        lines.append(f'  {code}: [{", ".join(cells)}],')
    data = "\n".join(lines)
    return TEMPLATE.replace("__DATA__", data)


TEMPLATE = '''// GENERATED by frontend/scripts/gen_schedule2026.py — do not edit the data block by
// hand; re-run the generator against the 2026-27 NFL schedule xlsx to update. Static,
// dependency-free (no runtime xlsx parser in the bundle). Opponent codes match our
// Sleeper codes / byeWeeks.ts BYE_WEEKS_2026; "BYE" marks a bye week.
//
// Schedule-strength note (E3 brief): the pipeline's defensive scoring
// (pipeline/models/scoring.py score_defense, backtest pbp_defense.team_week_dst) is
// Python and NOT published to the frontend, so scheduleStrength() takes an optional
// per-team defRatings map (0..1, lower = tougher) and otherwise degrades to a neutral
// 0.5 with covered=false. No new def-vs-position model is built here — the opponent
// lookup is this module's real, always-shipping value.

export const REGULAR_SEASON_WEEKS = 18;
/** Fantasy playoff weeks (standard 3-week bracket). */
export const PLAYOFF_WEEKS: readonly number[] = [15, 16, 17];

/**
 * One team-week. `opponent === "BYE"` means a bye. `home === null` on a real
 * opponent marks a neutral-site (international) game where the xlsx carries no
 * home/away — treat as neutral, not home. Otherwise `home` is true/false.
 */
export type WeekGame =
  | { opponent: string; home: boolean | null }
  | { opponent: "BYE"; home: null };

/** Team code -> 18 weeks, index i = week (i + 1). */
export const SCHEDULE_2026: Record<string, WeekGame[]> = {
__DATA__
};

const isBye = (g: WeekGame | undefined): boolean => !g || g.opponent === "BYE";

/** Opponent code for a team's week, "BYE" on a bye, or null if out of range/unknown team. */
export function opponentFor(team: string, week: number): string | null {
  const wk = SCHEDULE_2026[team]?.[week - 1];
  return wk ? wk.opponent : null;
}

export type RemainingGame = { week: number; opponent: string; home: boolean | null };

/** Games from `fromWeek` (inclusive) through week 18, byes included. */
export function remainingSchedule(team: string, fromWeek: number): RemainingGame[] {
  const games = SCHEDULE_2026[team];
  if (!games) return [];
  const start = Math.max(1, fromWeek);
  const out: RemainingGame[] = [];
  for (let w = start; w <= REGULAR_SEASON_WEEKS; w++) {
    const g = games[w - 1];
    if (g) out.push({ week: w, opponent: g.opponent, home: g.home });
  }
  return out;
}

/** Playoff-week opponents (weeks 15-17); byes surface as "BYE". */
export function playoffOpponents(team: string): string[] {
  const games = SCHEDULE_2026[team];
  if (!games) return [];
  return PLAYOFF_WEEKS.map((w) => games[w - 1]?.opponent ?? "BYE");
}

export type StrengthResult = {
  /** 0..1, higher = easier schedule (weaker opponents). Neutral 0.5 when uncovered. */
  strength: number;
  /** Fraction of scored weeks that had a real defRating (0 when defaulted neutral). */
  covered: number;
};

/**
 * Mean opponent easiness over `weeks` for a team. `defRatings[opp]` is that opponent
 * defense's strength in 0..1 where LOWER = tougher; easiness = 1 - rating. Byes and
 * unknown opponents are skipped. Missing ratings default to neutral 0.5 (easiness 0.5)
 * and lower `covered`. With no defRatings the result is a flat neutral 0.5, covered 0.
 */
export function scheduleStrength(
  team: string,
  weeks: number[],
  defRatings?: Record<string, number>,
): StrengthResult {
  const games = SCHEDULE_2026[team];
  if (!games) return { strength: 0.5, covered: 0 };
  let sum = 0;
  let n = 0;
  let hits = 0;
  for (const w of weeks) {
    const g = games[w - 1];
    if (isBye(g) || !g) continue;
    n++;
    const rating = defRatings?.[g.opponent];
    if (rating != null) {
      hits++;
      sum += 1 - rating;
    } else {
      sum += 0.5;
    }
  }
  if (n === 0) return { strength: 0.5, covered: 0 };
  return { strength: sum / n, covered: hits / n };
}

export type PlayoffSchedule = {
  team: string | null;
  games: RemainingGame[];
  /** Opponent easiness across playoff weeks (see scheduleStrength). */
  strength: number;
  covered: number;
};

/**
 * Playoff-week (15-17) schedule + strength for a player, keyed by nfl_team. E4 consumer.
 * Unknown/absent team → empty games, neutral strength.
 */
export function playoffSchedule(
  player: { nfl_team?: string | null },
  defRatings?: Record<string, number>,
): PlayoffSchedule {
  const team = player.nfl_team ?? null;
  if (!team || !SCHEDULE_2026[team]) {
    return { team, games: [], strength: 0.5, covered: 0 };
  }
  const games: RemainingGame[] = PLAYOFF_WEEKS.map((w) => {
    const g = SCHEDULE_2026[team][w - 1];
    return { week: w, opponent: g.opponent, home: g.home };
  });
  const { strength, covered } = scheduleStrength(team, [...PLAYOFF_WEEKS], defRatings);
  return { team, games, strength, covered };
}

/** The bye week (1..18) for a team per this schedule, or null if none found. */
export function byeWeekFor(team: string): number | null {
  const games = SCHEDULE_2026[team];
  if (!games) return null;
  const i = games.findIndex((g) => g.opponent === "BYE");
  return i >= 0 ? i + 1 : null;
}
'''


def main() -> None:
    xlsx = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_XLSX
    if not Path(xlsx).exists():
        raise SystemExit(f"xlsx not found: {xlsx}")
    OUT.write_text(emit(parse(xlsx)))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
