// GENERATED by frontend/scripts/gen_schedule2026.py — do not edit the data block by
// hand; re-run the generator against the 2026-27 NFL schedule xlsx to update. Static,
// dependency-free (no runtime xlsx parser in the bundle). Opponent codes match our
// Sleeper codes / byeWeeks.ts BYE_WEEKS_2026; "BYE" marks a bye week.
//
// Schedule-strength note (E3 brief): the pipeline's defensive scoring
// (pipeline/models/scoring.py score_defense, backtest pbp_defense.team_week_dst) is
// Python and NOT published to the frontend, so scheduleStrength() takes an optional
// per-team defRatings map (0..1, lower = tougher) and otherwise degrades to a neutral
// 0.5 with covered=false. No new def-vs-position model is built here — the opponent
// lookup is this module's real, always-shipping value.

export const REGULAR_SEASON_WEEKS = 18;
/** Fantasy playoff weeks (standard 3-week bracket). */
export const PLAYOFF_WEEKS: readonly number[] = [15, 16, 17];

/**
 * One team-week. `opponent === "BYE"` means a bye. `home === null` on a real
 * opponent marks a neutral-site (international) game where the xlsx carries no
 * home/away — treat as neutral, not home. Otherwise `home` is true/false.
 */
export type WeekGame =
  | { opponent: string; home: boolean | null }
  | { opponent: "BYE"; home: null };

/** Team code -> 18 weeks, index i = week (i + 1). */
export const SCHEDULE_2026: Record<string, WeekGame[]> = {
  ARI: [{ opponent: "LAC", home: false }, { opponent: "SEA", home: true }, { opponent: "SF", home: false }, { opponent: "NYG", home: false }, { opponent: "DET", home: true }, { opponent: "LAR", home: false }, { opponent: "DEN", home: true }, { opponent: "DAL", home: false }, { opponent: "SEA", home: false }, { opponent: "LAR", home: true }, { opponent: "KC", home: false }, { opponent: "WAS", home: true }, { opponent: "PHI", home: true }, { opponent: "BYE", home: null }, { opponent: "NYJ", home: true }, { opponent: "NO", home: false }, { opponent: "LV", home: true }, { opponent: "SF", home: true }],
  ATL: [{ opponent: "PIT", home: false }, { opponent: "CAR", home: true }, { opponent: "GB", home: false }, { opponent: "NO", home: false }, { opponent: "BAL", home: true }, { opponent: "CHI", home: true }, { opponent: "SF", home: true }, { opponent: "TB", home: false }, { opponent: "CIN", home: null }, { opponent: "KC", home: true }, { opponent: "BYE", home: null }, { opponent: "MIN", home: false }, { opponent: "DET", home: true }, { opponent: "CLE", home: false }, { opponent: "WAS", home: false }, { opponent: "TB", home: true }, { opponent: "NO", home: true }, { opponent: "CAR", home: false }],
  BAL: [{ opponent: "IND", home: false }, { opponent: "NO", home: true }, { opponent: "DAL", home: false }, { opponent: "TEN", home: true }, { opponent: "ATL", home: false }, { opponent: "CLE", home: false }, { opponent: "CIN", home: true }, { opponent: "BUF", home: false }, { opponent: "JAX", home: true }, { opponent: "LAC", home: true }, { opponent: "CAR", home: false }, { opponent: "HOU", home: false }, { opponent: "BYE", home: null }, { opponent: "TB", home: true }, { opponent: "PIT", home: false }, { opponent: "CLE", home: true }, { opponent: "CIN", home: false }, { opponent: "PIT", home: true }],
  BUF: [{ opponent: "HOU", home: false }, { opponent: "DET", home: true }, { opponent: "LAC", home: true }, { opponent: "NE", home: true }, { opponent: "LAR", home: false }, { opponent: "LV", home: false }, { opponent: "BYE", home: null }, { opponent: "BAL", home: true }, { opponent: "MIN", home: false }, { opponent: "NYJ", home: false }, { opponent: "MIA", home: true }, { opponent: "KC", home: true }, { opponent: "NE", home: false }, { opponent: "GB", home: false }, { opponent: "CHI", home: true }, { opponent: "DEN", home: false }, { opponent: "MIA", home: false }, { opponent: "NYJ", home: true }],
  CAR: [{ opponent: "CHI", home: true }, { opponent: "ATL", home: false }, { opponent: "CLE", home: false }, { opponent: "DET", home: true }, { opponent: "BYE", home: null }, { opponent: "PHI", home: false }, { opponent: "TB", home: true }, { opponent: "GB", home: false }, { opponent: "DEN", home: true }, { opponent: "NO", home: false }, { opponent: "BAL", home: true }, { opponent: "TB", home: false }, { opponent: "MIN", home: false }, { opponent: "NO", home: true }, { opponent: "CIN", home: true }, { opponent: "PIT", home: false }, { opponent: "SEA", home: true }, { opponent: "ATL", home: true }],
  CHI: [{ opponent: "CAR", home: false }, { opponent: "MIN", home: true }, { opponent: "PHI", home: true }, { opponent: "NYJ", home: true }, { opponent: "GB", home: false }, { opponent: "ATL", home: false }, { opponent: "NE", home: true }, { opponent: "SEA", home: false }, { opponent: "TB", home: true }, { opponent: "BYE", home: null }, { opponent: "NO", home: true }, { opponent: "DET", home: false }, { opponent: "JAX", home: true }, { opponent: "MIA", home: false }, { opponent: "BUF", home: false }, { opponent: "GB", home: true }, { opponent: "DET", home: true }, { opponent: "MIN", home: false }],
  CIN: [{ opponent: "TB", home: true }, { opponent: "HOU", home: false }, { opponent: "PIT", home: false }, { opponent: "JAX", home: true }, { opponent: "MIA", home: false }, { opponent: "BYE", home: null }, { opponent: "BAL", home: false }, { opponent: "TEN", home: true }, { opponent: "ATL", home: null }, { opponent: "PIT", home: true }, { opponent: "WAS", home: false }, { opponent: "NO", home: true }, { opponent: "CLE", home: false }, { opponent: "KC", home: true }, { opponent: "CAR", home: false }, { opponent: "IND", home: false }, { opponent: "BAL", home: true }, { opponent: "CLE", home: true }],
  CLE: [{ opponent: "JAX", home: false }, { opponent: "TB", home: false }, { opponent: "CAR", home: true }, { opponent: "PIT", home: true }, { opponent: "NYJ", home: false }, { opponent: "BAL", home: true }, { opponent: "TEN", home: false }, { opponent: "PIT", home: false }, { opponent: "NO", home: false }, { opponent: "HOU", home: true }, { opponent: "BYE", home: null }, { opponent: "LV", home: true }, { opponent: "CIN", home: true }, { opponent: "ATL", home: true }, { opponent: "NYG", home: false }, { opponent: "BAL", home: false }, { opponent: "IND", home: true }, { opponent: "CIN", home: false }],
  DAL: [{ opponent: "NYG", home: false }, { opponent: "WAS", home: true }, { opponent: "BAL", home: true }, { opponent: "HOU", home: false }, { opponent: "TB", home: true }, { opponent: "GB", home: false }, { opponent: "PHI", home: false }, { opponent: "ARI", home: true }, { opponent: "IND", home: false }, { opponent: "SF", home: true }, { opponent: "TEN", home: true }, { opponent: "PHI", home: true }, { opponent: "SEA", home: false }, { opponent: "BYE", home: null }, { opponent: "LAR", home: false }, { opponent: "JAX", home: true }, { opponent: "NYG", home: true }, { opponent: "WAS", home: false }],
  DEN: [{ opponent: "KC", home: false }, { opponent: "JAX", home: true }, { opponent: "LAR", home: true }, { opponent: "SF", home: false }, { opponent: "LAC", home: false }, { opponent: "SEA", home: true }, { opponent: "ARI", home: false }, { opponent: "KC", home: true }, { opponent: "CAR", home: false }, { opponent: "BYE", home: null }, { opponent: "LV", home: true }, { opponent: "PIT", home: false }, { opponent: "MIA", home: true }, { opponent: "NYJ", home: false }, { opponent: "LV", home: false }, { opponent: "BUF", home: true }, { opponent: "NE", home: false }, { opponent: "LAC", home: true }],
  DET: [{ opponent: "NO", home: true }, { opponent: "BUF", home: false }, { opponent: "NYJ", home: true }, { opponent: "CAR", home: false }, { opponent: "ARI", home: false }, { opponent: "BYE", home: null }, { opponent: "GB", home: true }, { opponent: "MIN", home: true }, { opponent: "MIA", home: false }, { opponent: "NE", home: true }, { opponent: "TB", home: true }, { opponent: "CHI", home: true }, { opponent: "ATL", home: false }, { opponent: "TEN", home: true }, { opponent: "MIN", home: false }, { opponent: "NYG", home: true }, { opponent: "CHI", home: false }, { opponent: "GB", home: false }],
  GB: [{ opponent: "MIN", home: false }, { opponent: "NYJ", home: false }, { opponent: "ATL", home: true }, { opponent: "TB", home: false }, { opponent: "CHI", home: true }, { opponent: "DAL", home: true }, { opponent: "DET", home: false }, { opponent: "CAR", home: true }, { opponent: "NE", home: false }, { opponent: "MIN", home: true }, { opponent: "BYE", home: null }, { opponent: "LAR", home: false }, { opponent: "NO", home: false }, { opponent: "BUF", home: true }, { opponent: "MIA", home: true }, { opponent: "CHI", home: false }, { opponent: "HOU", home: true }, { opponent: "DET", home: true }],
  HOU: [{ opponent: "BUF", home: true }, { opponent: "CIN", home: true }, { opponent: "IND", home: false }, { opponent: "DAL", home: true }, { opponent: "TEN", home: false }, { opponent: "JAX", home: false }, { opponent: "NYG", home: true }, { opponent: "BYE", home: null }, { opponent: "LAC", home: false }, { opponent: "CLE", home: false }, { opponent: "IND", home: true }, { opponent: "BAL", home: true }, { opponent: "PIT", home: false }, { opponent: "WAS", home: false }, { opponent: "JAX", home: true }, { opponent: "PHI", home: false }, { opponent: "GB", home: false }, { opponent: "TEN", home: true }],
  IND: [{ opponent: "BAL", home: true }, { opponent: "KC", home: false }, { opponent: "HOU", home: true }, { opponent: "WAS", home: false }, { opponent: "PIT", home: false }, { opponent: "TEN", home: true }, { opponent: "MIN", home: false }, { opponent: "JAX", home: false }, { opponent: "DAL", home: true }, { opponent: "MIA", home: true }, { opponent: "HOU", home: false }, { opponent: "NYG", home: true }, { opponent: "BYE", home: null }, { opponent: "PHI", home: false }, { opponent: "TEN", home: false }, { opponent: "CIN", home: true }, { opponent: "CLE", home: false }, { opponent: "JAX", home: true }],
  JAX: [{ opponent: "CLE", home: true }, { opponent: "DEN", home: false }, { opponent: "NE", home: true }, { opponent: "CIN", home: false }, { opponent: "PHI", home: true }, { opponent: "HOU", home: true }, { opponent: "BYE", home: null }, { opponent: "IND", home: true }, { opponent: "BAL", home: false }, { opponent: "TEN", home: false }, { opponent: "NYG", home: false }, { opponent: "TEN", home: true }, { opponent: "CHI", home: false }, { opponent: "PIT", home: true }, { opponent: "HOU", home: false }, { opponent: "DAL", home: false }, { opponent: "WAS", home: true }, { opponent: "IND", home: false }],
  KC: [{ opponent: "DEN", home: true }, { opponent: "IND", home: true }, { opponent: "MIA", home: false }, { opponent: "LV", home: false }, { opponent: "BYE", home: null }, { opponent: "LAC", home: true }, { opponent: "SEA", home: false }, { opponent: "DEN", home: false }, { opponent: "NYJ", home: true }, { opponent: "ATL", home: false }, { opponent: "ARI", home: true }, { opponent: "BUF", home: false }, { opponent: "LAR", home: false }, { opponent: "CIN", home: false }, { opponent: "NE", home: true }, { opponent: "SF", home: true }, { opponent: "LAC", home: false }, { opponent: "LV", home: true }],
  LAC: [{ opponent: "ARI", home: true }, { opponent: "LV", home: true }, { opponent: "BUF", home: false }, { opponent: "SEA", home: false }, { opponent: "DEN", home: true }, { opponent: "KC", home: false }, { opponent: "BYE", home: null }, { opponent: "LAR", home: false }, { opponent: "HOU", home: true }, { opponent: "BAL", home: false }, { opponent: "NYJ", home: true }, { opponent: "NE", home: true }, { opponent: "TB", home: false }, { opponent: "LV", home: false }, { opponent: "SF", home: true }, { opponent: "MIA", home: false }, { opponent: "KC", home: true }, { opponent: "DEN", home: false }],
  LAR: [{ opponent: "SF", home: true }, { opponent: "NYG", home: true }, { opponent: "DEN", home: false }, { opponent: "PHI", home: false }, { opponent: "BUF", home: true }, { opponent: "ARI", home: true }, { opponent: "LV", home: false }, { opponent: "LAC", home: true }, { opponent: "WAS", home: false }, { opponent: "ARI", home: false }, { opponent: "BYE", home: null }, { opponent: "GB", home: true }, { opponent: "KC", home: true }, { opponent: "SF", home: false }, { opponent: "DAL", home: true }, { opponent: "SEA", home: false }, { opponent: "TB", home: false }, { opponent: "SEA", home: true }],
  LV: [{ opponent: "MIA", home: true }, { opponent: "LAC", home: false }, { opponent: "NO", home: false }, { opponent: "KC", home: true }, { opponent: "NE", home: false }, { opponent: "BUF", home: true }, { opponent: "LAR", home: true }, { opponent: "NYJ", home: false }, { opponent: "SF", home: false }, { opponent: "SEA", home: true }, { opponent: "DEN", home: false }, { opponent: "CLE", home: false }, { opponent: "BYE", home: null }, { opponent: "LAC", home: true }, { opponent: "DEN", home: true }, { opponent: "TEN", home: true }, { opponent: "ARI", home: false }, { opponent: "KC", home: false }],
  MIA: [{ opponent: "LV", home: false }, { opponent: "SF", home: false }, { opponent: "KC", home: true }, { opponent: "MIN", home: false }, { opponent: "CIN", home: true }, { opponent: "BYE", home: null }, { opponent: "NYJ", home: false }, { opponent: "NE", home: true }, { opponent: "DET", home: true }, { opponent: "IND", home: false }, { opponent: "BUF", home: false }, { opponent: "NYJ", home: true }, { opponent: "DEN", home: false }, { opponent: "CHI", home: true }, { opponent: "GB", home: false }, { opponent: "LAC", home: true }, { opponent: "BUF", home: true }, { opponent: "NE", home: false }],
  MIN: [{ opponent: "GB", home: true }, { opponent: "CHI", home: false }, { opponent: "TB", home: false }, { opponent: "MIA", home: true }, { opponent: "NO", home: false }, { opponent: "BYE", home: null }, { opponent: "IND", home: true }, { opponent: "DET", home: false }, { opponent: "BUF", home: true }, { opponent: "GB", home: false }, { opponent: "SF", home: false }, { opponent: "ATL", home: true }, { opponent: "CAR", home: true }, { opponent: "NE", home: false }, { opponent: "DET", home: true }, { opponent: "WAS", home: true }, { opponent: "NYJ", home: false }, { opponent: "CHI", home: true }],
  NE: [{ opponent: "SEA", home: false }, { opponent: "PIT", home: true }, { opponent: "JAX", home: false }, { opponent: "BUF", home: false }, { opponent: "LV", home: true }, { opponent: "NYJ", home: true }, { opponent: "CHI", home: false }, { opponent: "MIA", home: false }, { opponent: "GB", home: true }, { opponent: "DET", home: false }, { opponent: "BYE", home: null }, { opponent: "LAC", home: false }, { opponent: "BUF", home: true }, { opponent: "MIN", home: true }, { opponent: "KC", home: false }, { opponent: "NYJ", home: false }, { opponent: "DEN", home: true }, { opponent: "MIA", home: true }],
  NO: [{ opponent: "DET", home: false }, { opponent: "BAL", home: false }, { opponent: "LV", home: true }, { opponent: "ATL", home: true }, { opponent: "MIN", home: true }, { opponent: "NYG", home: false }, { opponent: "PIT", home: true }, { opponent: "BYE", home: null }, { opponent: "CLE", home: true }, { opponent: "CAR", home: true }, { opponent: "CHI", home: false }, { opponent: "CIN", home: false }, { opponent: "GB", home: true }, { opponent: "CAR", home: false }, { opponent: "TB", home: false }, { opponent: "ARI", home: true }, { opponent: "ATL", home: false }, { opponent: "TB", home: true }],
  NYG: [{ opponent: "DAL", home: true }, { opponent: "LAR", home: false }, { opponent: "TEN", home: true }, { opponent: "ARI", home: true }, { opponent: "WAS", home: false }, { opponent: "NO", home: true }, { opponent: "HOU", home: false }, { opponent: "BYE", home: null }, { opponent: "PHI", home: false }, { opponent: "WAS", home: true }, { opponent: "JAX", home: true }, { opponent: "IND", home: false }, { opponent: "SF", home: true }, { opponent: "SEA", home: false }, { opponent: "CLE", home: true }, { opponent: "DET", home: false }, { opponent: "DAL", home: false }, { opponent: "PHI", home: true }],
  NYJ: [{ opponent: "TEN", home: false }, { opponent: "GB", home: true }, { opponent: "DET", home: false }, { opponent: "CHI", home: false }, { opponent: "CLE", home: true }, { opponent: "NE", home: false }, { opponent: "MIA", home: true }, { opponent: "LV", home: true }, { opponent: "KC", home: false }, { opponent: "BUF", home: true }, { opponent: "LAC", home: false }, { opponent: "MIA", home: false }, { opponent: "BYE", home: null }, { opponent: "DEN", home: true }, { opponent: "ARI", home: false }, { opponent: "NE", home: true }, { opponent: "MIN", home: true }, { opponent: "BUF", home: false }],
  PHI: [{ opponent: "WAS", home: true }, { opponent: "TEN", home: false }, { opponent: "CHI", home: false }, { opponent: "LAR", home: true }, { opponent: "JAX", home: false }, { opponent: "CAR", home: true }, { opponent: "DAL", home: true }, { opponent: "WAS", home: false }, { opponent: "NYG", home: true }, { opponent: "BYE", home: null }, { opponent: "PIT", home: true }, { opponent: "DAL", home: false }, { opponent: "ARI", home: false }, { opponent: "IND", home: true }, { opponent: "SEA", home: true }, { opponent: "HOU", home: true }, { opponent: "SF", home: false }, { opponent: "NYG", home: false }],
  PIT: [{ opponent: "ATL", home: true }, { opponent: "NE", home: false }, { opponent: "CIN", home: true }, { opponent: "CLE", home: false }, { opponent: "IND", home: true }, { opponent: "TB", home: false }, { opponent: "NO", home: false }, { opponent: "CLE", home: true }, { opponent: "BYE", home: null }, { opponent: "CIN", home: false }, { opponent: "PHI", home: false }, { opponent: "DEN", home: true }, { opponent: "HOU", home: true }, { opponent: "JAX", home: false }, { opponent: "BAL", home: true }, { opponent: "CAR", home: true }, { opponent: "TEN", home: false }, { opponent: "BAL", home: false }],
  SEA: [{ opponent: "NE", home: true }, { opponent: "ARI", home: false }, { opponent: "WAS", home: false }, { opponent: "LAC", home: true }, { opponent: "SF", home: true }, { opponent: "DEN", home: false }, { opponent: "KC", home: true }, { opponent: "CHI", home: true }, { opponent: "ARI", home: true }, { opponent: "LV", home: false }, { opponent: "BYE", home: null }, { opponent: "SF", home: false }, { opponent: "DAL", home: true }, { opponent: "NYG", home: true }, { opponent: "PHI", home: false }, { opponent: "LAR", home: true }, { opponent: "CAR", home: false }, { opponent: "LAR", home: false }],
  SF: [{ opponent: "LAR", home: false }, { opponent: "MIA", home: true }, { opponent: "ARI", home: true }, { opponent: "DEN", home: true }, { opponent: "SEA", home: false }, { opponent: "WAS", home: true }, { opponent: "ATL", home: false }, { opponent: "BYE", home: null }, { opponent: "LV", home: true }, { opponent: "DAL", home: false }, { opponent: "MIN", home: true }, { opponent: "SEA", home: true }, { opponent: "NYG", home: false }, { opponent: "LAR", home: true }, { opponent: "LAC", home: false }, { opponent: "KC", home: false }, { opponent: "PHI", home: true }, { opponent: "ARI", home: false }],
  TB: [{ opponent: "CIN", home: false }, { opponent: "CLE", home: true }, { opponent: "MIN", home: true }, { opponent: "GB", home: true }, { opponent: "DAL", home: false }, { opponent: "PIT", home: true }, { opponent: "CAR", home: false }, { opponent: "ATL", home: true }, { opponent: "CHI", home: false }, { opponent: "BYE", home: null }, { opponent: "DET", home: false }, { opponent: "CAR", home: true }, { opponent: "LAC", home: true }, { opponent: "BAL", home: false }, { opponent: "NO", home: true }, { opponent: "ATL", home: false }, { opponent: "LAR", home: true }, { opponent: "NO", home: false }],
  TEN: [{ opponent: "NYJ", home: true }, { opponent: "PHI", home: true }, { opponent: "NYG", home: false }, { opponent: "BAL", home: false }, { opponent: "HOU", home: true }, { opponent: "IND", home: false }, { opponent: "CLE", home: true }, { opponent: "CIN", home: false }, { opponent: "BYE", home: null }, { opponent: "JAX", home: true }, { opponent: "DAL", home: false }, { opponent: "JAX", home: false }, { opponent: "WAS", home: true }, { opponent: "DET", home: false }, { opponent: "IND", home: true }, { opponent: "LV", home: false }, { opponent: "PIT", home: true }, { opponent: "HOU", home: false }],
  WAS: [{ opponent: "PHI", home: false }, { opponent: "DAL", home: false }, { opponent: "SEA", home: true }, { opponent: "IND", home: true }, { opponent: "NYG", home: true }, { opponent: "SF", home: false }, { opponent: "BYE", home: null }, { opponent: "PHI", home: true }, { opponent: "LAR", home: true }, { opponent: "NYG", home: false }, { opponent: "CIN", home: true }, { opponent: "ARI", home: false }, { opponent: "TEN", home: false }, { opponent: "HOU", home: true }, { opponent: "ATL", home: true }, { opponent: "MIN", home: false }, { opponent: "JAX", home: false }, { opponent: "DAL", home: true }],
};

const isBye = (g: WeekGame | undefined): boolean => !g || g.opponent === "BYE";

/** Opponent code for a team's week, "BYE" on a bye, or null if out of range/unknown team. */
export function opponentFor(team: string, week: number): string | null {
  const wk = SCHEDULE_2026[team]?.[week - 1];
  return wk ? wk.opponent : null;
}

export type RemainingGame = { week: number; opponent: string; home: boolean | null };

/** Games from `fromWeek` (inclusive) through week 18, byes included. */
export function remainingSchedule(team: string, fromWeek: number): RemainingGame[] {
  const games = SCHEDULE_2026[team];
  if (!games) return [];
  const start = Math.max(1, fromWeek);
  const out: RemainingGame[] = [];
  for (let w = start; w <= REGULAR_SEASON_WEEKS; w++) {
    const g = games[w - 1];
    if (g) out.push({ week: w, opponent: g.opponent, home: g.home });
  }
  return out;
}

/** Playoff-week opponents (weeks 15-17); byes surface as "BYE". */
export function playoffOpponents(team: string): string[] {
  const games = SCHEDULE_2026[team];
  if (!games) return [];
  return PLAYOFF_WEEKS.map((w) => games[w - 1]?.opponent ?? "BYE");
}

export type StrengthResult = {
  /** 0..1, higher = easier schedule (weaker opponents). Neutral 0.5 when uncovered. */
  strength: number;
  /** Fraction of scored weeks that had a real defRating (0 when defaulted neutral). */
  covered: number;
};

/**
 * Mean opponent easiness over `weeks` for a team. `defRatings[opp]` is that opponent
 * defense's strength in 0..1 where LOWER = tougher; easiness = 1 - rating. Byes and
 * unknown opponents are skipped. Missing ratings default to neutral 0.5 (easiness 0.5)
 * and lower `covered`. With no defRatings the result is a flat neutral 0.5, covered 0.
 */
export function scheduleStrength(
  team: string,
  weeks: number[],
  defRatings?: Record<string, number>,
): StrengthResult {
  const games = SCHEDULE_2026[team];
  if (!games) return { strength: 0.5, covered: 0 };
  let sum = 0;
  let n = 0;
  let hits = 0;
  for (const w of weeks) {
    const g = games[w - 1];
    if (isBye(g) || !g) continue;
    n++;
    const rating = defRatings?.[g.opponent];
    if (rating != null) {
      hits++;
      sum += 1 - rating;
    } else {
      sum += 0.5;
    }
  }
  if (n === 0) return { strength: 0.5, covered: 0 };
  return { strength: sum / n, covered: hits / n };
}

export type PlayoffSchedule = {
  team: string | null;
  games: RemainingGame[];
  /** Opponent easiness across playoff weeks (see scheduleStrength). */
  strength: number;
  covered: number;
};

/**
 * Playoff-week (15-17) schedule + strength for a player, keyed by nfl_team. E4 consumer.
 * Unknown/absent team → empty games, neutral strength.
 */
export function playoffSchedule(
  player: { nfl_team?: string | null },
  defRatings?: Record<string, number>,
): PlayoffSchedule {
  const team = player.nfl_team ?? null;
  if (!team || !SCHEDULE_2026[team]) {
    return { team, games: [], strength: 0.5, covered: 0 };
  }
  const games: RemainingGame[] = PLAYOFF_WEEKS.map((w) => {
    const g = SCHEDULE_2026[team][w - 1];
    return { week: w, opponent: g.opponent, home: g.home };
  });
  const { strength, covered } = scheduleStrength(team, [...PLAYOFF_WEEKS], defRatings);
  return { team, games, strength, covered };
}

/** The bye week (1..18) for a team per this schedule, or null if none found. */
export function byeWeekFor(team: string): number | null {
  const games = SCHEDULE_2026[team];
  if (!games) return null;
  const i = games.findIndex((g) => g.opponent === "BYE");
  return i >= 0 ? i + 1 : null;
}
