// Row shapes mirroring db/schema.sql (the subset the frontend reads).

export type Position = "QB" | "RB" | "WR" | "TE" | "K" | "DEF";

export interface Player {
  id: string;
  sleeper_id: string;
  espn_id: string | null;
  full_name: string;
  position: Position | null;
  nfl_team: string | null;
  bye_week: number | null;
  age: number | null;
  years_exp: number | null;
  status: string | null;
  injury_status: string | null;
  metadata?: {
    depth_chart_order?: number | null;
    depth_chart_position?: string | null;
    /** Sleeper search popularity — search/display metadata ONLY; never a value input (C01). */
    search_rank?: number | null;
    [k: string]: unknown;
  } | null;
}

export interface PlayerValue {
  player_id: string;
  engine: "vorp" | "monte_carlo";
  value: number | null;
  vor: number | null;
  replacement: number | null;
  /** CEILING VOR = projection ceiling − replacement (C01 unit contract; NOT a raw ceiling —
   *  convert via lib/valueUnits.projectionCeiling before comparing with raw projections). */
  boom: number | null;
  /** FLOOR VOR = projection floor − replacement (same contract as boom). */
  bust: number | null;
  adp: number | null;
  rank: number | null;
  predictability?: number | null;   // ρ∈[0,1] (SCORING.md §1) — drives the predictability meter
}

// Player joined with its value for a given engine (Player Explorer row).
export interface PlayerWithValue extends Player {
  value?: PlayerValue | null;
}

export type Engine = PlayerValue["engine"];

// Auto-published modeling finding (Epic 9b). Rows are generated by the cron
// pipeline (pipeline/articles_generate.py) from E3's context artifact; E9a search
// indexes id/title/slug/summary. `body` is blank-line-separated prose paragraphs.
export interface Article {
  id: string;
  slug: string;
  title: string;
  summary: string;
  body: string;
  category: string;
  source: string | null;
  published_at: string | null;
}

// The card/list projection — the detail read adds `body`.
export type ArticleSummary = Omit<Article, "body">;

// A player_trends row (v4 E1): recent-window usage/role signals keyed to a
// player. Each field is 0..1 with 0.5 == neutral/flat, except routes_run (a
// route count). Feeds the bench scorer (lib/benchScore.ts) via
// queries.getPlayerTrends; shaped so the map is a drop-in `BenchCtx.trends`.
export interface PlayerTrends {
  player_id: string;
  opportunity_trend: number;
  target_share_trend: number;
  routes_run: number;
  routes_trend: number;
  starting_prob: number;
  job_security: number;
}

// A player_availability row (v5 E2b): the engine's `AvailabilityModel.p_startable`,
// published per (player_id, season, week). Read via queries.getAvailabilityMap into a
// flat `player_id -> p_startable` map for lib/availability.ts / draftAI.ts.
export interface PlayerAvailability {
  player_id: string;
  season: number;
  week: number;
  p_startable: number;
  roster_status: string | null;
  source: string;
}

// One bench player as surfaced in the war-room Bench panel (v4 E6): its 0-100
// BenchScore and whether it's the first body to drop (lowest value). The health
// band that colors the row is derived from `score` in the panel.
export interface BenchPanelEntry {
  id: string;
  name: string;
  position: string;
  score: number;
  dropFirst: boolean;
}
