// Row shapes mirroring db/schema.sql (the subset the frontend reads).

export type Position = "QB" | "RB" | "WR" | "TE" | "K" | "DEF";

export interface Player {
  id: string;
  sleeper_id: string;
  espn_id: string | null;
  full_name: string;
  position: Position | null;
  nfl_team: string | null;
  bye_week: number | null;
  age: number | null;
  years_exp: number | null;
  status: string | null;
  injury_status: string | null;
  metadata?: {
    depth_chart_order?: number | null;
    depth_chart_position?: string | null;
    search_rank?: number | null;
    [k: string]: unknown;
  } | null;
}

export interface PlayerValue {
  player_id: string;
  engine: "vorp" | "monte_carlo";
  value: number | null;
  vor: number | null;
  replacement: number | null;
  boom: number | null;
  bust: number | null;
  adp: number | null;
  rank: number | null;
  predictability?: number | null;   // ρ∈[0,1] (SCORING.md §1) — drives the predictability meter
}

// Player joined with its value for a given engine (Player Explorer row).
export interface PlayerWithValue extends Player {
  value?: PlayerValue | null;
}

export type Engine = PlayerValue["engine"];

// Auto-published modeling finding (Epic 9b). Rows are generated by the cron
// pipeline (pipeline/articles_generate.py) from E3's context artifact; E9a search
// indexes id/title/slug/summary. `body` is blank-line-separated prose paragraphs.
export interface Article {
  id: string;
  slug: string;
  title: string;
  summary: string;
  body: string;
  category: string;
  source: string | null;
  published_at: string | null;
}

// The card/list projection — the detail read adds `body`.
export type ArticleSummary = Omit<Article, "body">;
